orbs: # declare what orbs we are going to use
    node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

defaults: &defaults
  working_directory: ~/repo

jobs:
    core:
        <<: *defaults
        working_directory: ~/repo

      steps:
          - checkout

        -restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

        - run: npm ci

        - run: npm run test:ci

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - persist_to_workspace:
            root: ~/repo
            paths: .
      
workflows:
    version: 2
    core:
      jobs:
        - core:
            filters:
              branches:
                only:
                  - master
                  - dev
